"""books table

Revision ID: bad2af1d06f9
Revises: 
Create Date: 2019-07-12 15:01:11.678002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad2af1d06f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('loaned_to', sa.String(length=120), nullable=True),
    sa.Column('rfid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_loaned_to'), 'book', ['loaned_to'], unique=False)
    op.create_index(op.f('ix_book_rfid'), 'book', ['rfid'], unique=True)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_rfid'), table_name='book')
    op.drop_index(op.f('ix_book_loaned_to'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
